version: "3.8"

services:
  postgres:
    container_name: pg-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kronoos
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres